INSERT INTO `menu` VALUES (1, 'Entrar', 'index', 1);
INSERT INTO `menu` VALUES (2, 'Quem somos', 'quemsomos', 1);
INSERT INTO `menu` VALUES (3, 'Fale conosco', 'faleconosco', 1);
INSERT INTO `menu` VALUES (4, 'Cliente', 'cliente', 1);
INSERT INTO `menu` VALUES (5, 'Minha área', 'minhaarea', 1);
INSERT INTO `menu` VALUES (6, 'Sair', 'logoff', 1);
INSERT INTO `menu` VALUES (7, 'Editar Usuario', 'editarusu', 0);
INSERT INTO `menu` VALUES (8, 'Deletar Usuario', 'deletarusu', 0);
INSERT INTO `menu` VALUES (9, 'Visualizar Setores', 'setor', 0);
INSERT INTO `menu` VALUES (10, 'Visualizar Usuarios', 'usuario', 0);
INSERT INTO `menu` VALUES (11, 'Cadastrar Usuario', 'cadastrarusu', 0);
INSERT INTO `menu` VALUES (12, 'Editar Setor', 'editarsetor', 0);
INSERT INTO `menu` VALUES (13, 'Cadastrar Setor', 'cadastrarsetor', 0);
INSERT INTO `menu` VALUES (14, 'Deletar Setor', 'deletarsetor', 0);
INSERT INTO `menu` VALUES (15, 'Requisições', 'requisicoes', 1);
INSERT INTO `menu` VALUES (16, 'Visualizar Material', 'material', 0);
INSERT INTO `menu` VALUES (17, 'Visualizar Requisições', 'requisicao', 0);
INSERT INTO `menu` VALUES (18, 'Cadastrar Material', 'cadastrarmaterial', 0);
INSERT INTO `menu` VALUES (19, 'Cadastrar Requisição', 'cadastrarrequisicao', 0);
INSERT INTO `menu` VALUES (20, 'Deletar Material', 'deletarmaterial', 0);
INSERT INTO `menu` VALUES (21, 'Deletar Requisição', 'deletarrequisicao', 0);
INSERT INTO `menu` VALUES (22, 'Editar Material', 'editarmaterial', 0);
INSERT INTO `menu` VALUES (23, 'Editar Requisição', 'editarrequisicao', 0);
